version: '3.9'

name: barky-dev

services:
  mysql:
    image: mysql:8.0
    container_name: barky_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    ports:
      - "3307:3306"
